from fastapi import APIRouter, Depends
from typing import List, Dict
from services.ml_engine import ml_engine
from reportlab.pdfgen import canvas
from fastapi.responses import FileResponse
import os
import numpy as np
from sklearn.linear_model import LinearRegression

router = APIRouter(tags=["Analytics"])

@router.get("/analytics/anomalies")
def get_anomalies():
    # Mock data stream
    data_points = [{"time": i, "value": abs(np.random.normal(100, 20))} for i in range(50)]
    # Add some outliers
    data_points[10]["value"] = 300
    data_points[35]["value"] = 400
    
    anomalies_mask = ml_engine.detect_anomalies(data_points)
    
    result = []
    for i, point in enumerate(data_points):
        result.append({
            "time": point["time"],
            "value": point["value"],
            "is_anomaly": bool(anomalies_mask[i]) if i < len(anomalies_mask) else False
        })
    return result

@router.get("/analytics/forecast")
def get_forecast():
    # Mock Sales/Traffic Data
    X = np.array(range(50)).reshape(-1, 1)
    y = 2 * X.flatten() + 50 + np.random.normal(0, 10, 50) # Linear trend
    
    model = LinearRegression()
    model.fit(X, y)
    
    # Predict next 10 days
    X_future = np.array(range(50, 60)).reshape(-1, 1)
    y_future = model.predict(X_future)
    
    historical = [{"day": int(x), "value": float(val), "type": "history"} for x, val in zip(X.flatten(), y)]
    forecast = [{"day": int(x), "value": float(val), "type": "forecast"} for x, val in zip(X_future.flatten(), y_future)]
    
    return historical + forecast

@router.get("/analytics/report")
def generate_pdf_report():
    filepath = "analytics_report.pdf"
    p = canvas.Canvas(filepath)
    p.drawString(100, 800, "CONFIDENTIAL ANALYTICS REPORT")
    p.drawString(100, 780, "Generated by NEXUS Intel System")
    p.drawString(100, 750, "Summary of Findings:")
    p.drawString(100, 730, "- Anomaly detection scan completed.")
    p.drawString(100, 715, "- Forecast indicates 20% growth in data ingestion.")
    p.drawString(100, 700, "- Threat level: MODERATE.")
    p.save()
    return FileResponse(filepath, media_type='application/pdf', filename="report.pdf")
